# Gitleaks configuration for CryptoSmartTrader V2

title = "CryptoSmartTrader V2 Secrets Detection"

[extend]
# Extend default gitleaks rules
useDefault = true

[[rules]]
id = "crypto-api-keys"
description = "Cryptocurrency exchange API keys"
regex = '''(?i)(kraken|binance|coinbase|kucoin|huobi)[_-]?api[_-]?key['":\s]*[=:]\s*['"][a-zA-Z0-9/+=]{20,}['"]'''
keywords = [
    "kraken_api_key",
    "binance_api_key", 
    "coinbase_api_key",
    "kucoin_api_key",
    "huobi_api_key"
]

[[rules]]
id = "crypto-secret-keys"
description = "Cryptocurrency exchange secret keys"
regex = '''(?i)(kraken|binance|coinbase|kucoin|huobi)[_-]?secret[_-]?key['":\s]*[=:]\s*['"][a-zA-Z0-9/+=]{20,}['"]'''
keywords = [
    "kraken_secret",
    "binance_secret",
    "coinbase_secret", 
    "kucoin_secret",
    "huobi_secret"
]

[[rules]]
id = "openai-api-keys"
description = "OpenAI API keys"
regex = '''sk-[a-zA-Z0-9]{48}'''
keywords = ["openai", "gpt", "chatgpt"]

[[rules]]
id = "anthropic-api-keys"
description = "Anthropic API keys"
regex = '''sk-ant-[a-zA-Z0-9\-_]{95}'''
keywords = ["anthropic", "claude"]

[[rules]]
id = "telegram-bot-tokens"
description = "Telegram bot tokens"
regex = '''[0-9]{8,10}:[a-zA-Z0-9_-]{35}'''
keywords = ["telegram", "bot", "token"]

[[rules]]
id = "database-urls"
description = "Database connection URLs"
regex = '''(?i)(postgres|mysql|mongodb)://[^\s'"`]{10,}'''
keywords = ["postgres://", "mysql://", "mongodb://"]

[[rules]]
id = "private-keys"
description = "Private keys"
regex = '''-----BEGIN[A-Z ]*PRIVATE KEY-----[A-Za-z0-9+/=\s]*-----END[A-Z ]*PRIVATE KEY-----'''
keywords = ["private key", "rsa", "dsa", "ec", "openssh"]

[allowlist]
description = "Global allowlist for false positives"
paths = [
    '''\.env\.example$''',
    '''\.env\.template$''',
    '''README\.md$''',
    '''docs/.*''',
    '''tests/.*test.*\.py$''',
    '''\.gitleaks\.toml$'''
]

regexes = [
    '''(?i)example[_-]?api[_-]?key''',
    '''(?i)test[_-]?api[_-]?key''',
    '''(?i)dummy[_-]?secret''',
    '''(?i)placeholder[_-]?token''',
    '''(?i)fake[_-]?password''',
    '''sk-test-[a-zA-Z0-9]{48}''',
    '''YOUR_API_KEY_HERE''',
    '''<API_KEY>''',
    '''\*\*\*\*\*\*\*\*''',
    '''xxx''',
    '''yyy''',
    '''zzz'''
]