# Ruff configuration for CryptoSmartTrader V2
target-version = "py311"
line-length = 100
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "S",   # bandit (security)
    "T20", # flake8-print
]

ignore = [
    "E501",  # line too long (handled by black)
    "B008",  # function calls in argument defaults
    "S101",  # assert statements (needed for tests)
    "T201",  # print statements (needed for debugging)
]

[per-file-ignores]
"__init__.py" = ["F401", "F403"]  # Allow unused imports
"tests/*" = ["S101", "S106"]      # Allow assert and hardcoded passwords in tests
"experiments/*" = ["F401", "F841"] # Allow experimental code patterns

[mccabe]
max-complexity = 10

[isort]
force-single-line = false
multi-line-output = 3
include-trailing-comma = true