name: Branch Protection Setup

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to protect'
        required: true
        default: 'main'
        type: string

jobs:
  setup-protection:
    name: Setup Branch Protection
    runs-on: ubuntu-latest
    permissions:
      administration: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Branch Protection Rules
        uses: actions/github-script@v7
        with:
          script: |
            const branch = '${{ inputs.branch }}' || 'main';
            
            const protection = {
              required_status_checks: {
                strict: true,
                contexts: [
                  'Security Scanning',
                  'Test (Python 3.11)',
                  'Test (Python 3.12)', 
                  'Quality Gates'
                ]
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                require_last_push_approval: true
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false,
              block_creations: false,
              required_conversation_resolution: true,
              lock_branch: false,
              allow_fork_syncing: true
            };
            
            try {
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: branch,
                ...protection
              });
              
              console.log(`✅ Branch protection rules applied to ${branch}`);
            } catch (error) {
              console.error(`❌ Failed to apply branch protection: ${error.message}`);
              throw error;
            }