# Kubernetes Deployment for CryptoSmartTrader V2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptosmarttrader
  namespace: cryptosmarttrader
  labels:
    app: cryptosmarttrader
    version: v2.0.0
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: cryptosmarttrader
  template:
    metadata:
      labels:
        app: cryptosmarttrader
        version: v2.0.0
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      
      containers:
      - name: cryptosmarttrader
        image: cryptosmarttrader:v2.0.0
        imagePullPolicy: Always
        
        ports:
        - name: dashboard
          containerPort: 5000
          protocol: TCP
        - name: api
          containerPort: 8001
          protocol: TCP
        - name: metrics
          containerPort: 8000
          protocol: TCP
        
        # Environment configuration
        envFrom:
        - configMapRef:
            name: cryptosmarttrader-config
        - secretRef:
            name: cryptosmarttrader-secrets
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        # Startup probe for slow initialization
        startupProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12  # Allow 2 minutes for startup
        
        # Resource limits
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        
        # Security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        
        # Volume mounts
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: logs-volume
          mountPath: /app/logs
        - name: models-volume
          mountPath: /app/models
        - name: cache-volume
          mountPath: /app/cache
        - name: tmp-volume
          mountPath: /tmp
      
      # Volumes
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: cryptosmarttrader-data
      - name: logs-volume
        persistentVolumeClaim:
          claimName: cryptosmarttrader-logs
      - name: models-volume
        persistentVolumeClaim:
          claimName: cryptosmarttrader-models
      - name: cache-volume
        emptyDir:
          sizeLimit: 1Gi
      - name: tmp-volume
        emptyDir:
          sizeLimit: 500Mi
      
      # Restart policy
      restartPolicy: Always