# Persistent Volume Claims for CryptoSmartTrader V2
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cryptosmarttrader-data
  namespace: cryptosmarttrader
  labels:
    app: cryptosmarttrader
    component: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cryptosmarttrader-logs
  namespace: cryptosmarttrader
  labels:
    app: cryptosmarttrader
    component: logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cryptosmarttrader-models
  namespace: cryptosmarttrader
  labels:
    app: cryptosmarttrader
    component: models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard