# Ruff configuration
target-version = "py311"
line-length = 100
indent-width = 4

# Include source directories
include = ["src/**/*.py", "tests/**/*.py", "*.py"]

# Exclude cache and build directories  
exclude = [
    ".cache",
    "__pycache__",
    ".git",
    ".mypy_cache",
    ".pytest_cache", 
    ".ruff_cache",
    ".venv",
    "build",
    "dist",
    "venv",
    "attached_assets",
    "exports"
]

[lint]
# Enable comprehensive rule set for enterprise-grade code
select = [
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings  
    "F",      # Pyflakes
    "I",      # isort
    "UP",     # pyupgrade
    "B",      # flake8-bugbear
    "C4",     # flake8-comprehensions
    "PIE",    # flake8-pie
    "SIM",    # flake8-simplify
    "TID",    # flake8-tidy-imports
]

# Ignore specific rules for flexibility
ignore = [
    "E501",   # line too long (handled by formatter)
    "B008",   # function calls in argument defaults
    "B905",   # zip strict argument
    "SIM108", # use ternary operator (sometimes less readable)
]

[lint.per-file-ignores]
"tests/**/*.py" = ["B011", "PIE796"]  # Allow assert, use of GLOALS
"**/__init__.py" = ["F401"]           # Allow unused imports

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"