name: Branch Protection Setup

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  setup-branch-protection:
    name: Configure Branch Protection
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Branch Protection Rules
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Configure branch protection for main branch
            try {
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'main',
                required_status_checks: {
                  strict: true,
                  contexts: [
                    'Code Quality',
                    'Tests & Coverage', 
                    'Build Validation',
                    'CI Success'
                  ]
                },
                enforce_admins: false,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: true
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false
              });
              
              console.log('✅ Branch protection configured for main branch');
              
              // Required status checks that must pass
              const requiredChecks = [
                'Code Quality',      // ruff, black, mypy
                'Tests & Coverage',  // pytest --cov --fail-under=70
                'Build Validation'   // Package build + import validation
              ];
              
              console.log('📋 Required status checks:', requiredChecks);
              console.log('🔒 Security scans configured as non-blocking');
              
            } catch (error) {
              console.error('❌ Failed to configure branch protection:', error);
              throw error;
            }