[server]
headless = true
address = "0.0.0.0"
port = 5001

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1e3a5f"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"